sudo: required
dist: trusty
language: c

script: make && make test || ./test/test_zappy_server 2>/dev/null

install: .ci/install.sh

os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - os: linux

notifications:
  slack: dwarfoftherap:cIctwvXXMVkBmwNLxAkA6Y2g
