sudo: required 
language: c

script: make test

install: .ci/install.sh

os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - os: linux

notifications:
  slack: dwarfoftherap:cIctwvXXMVkBmwNLxAkA6Y2g
